import Navbar from './navbar'
import Footer from './footer'
import Head from 'next/head'
import { Box } from '@chakra-ui/react'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box  bg="green.700" minH="100vh" justifyContent="space-even">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </Box>
    </>
  )
}